.TH "synce-configure-bindings" 1 "SynCE" "http://www.synce.org/"
.SH NAME
synce-configure-bindings \- Configure binding configuration
.SH SYNOPSIS
.B synce-configure-bindings
.SH DESCRIPTION
.B synce-configure-bindings
allows you to configure the bindings with the device.
.SH "AUTHOR"
This man page was written by Jonny Lamb <jonnylamb@jonnylamb.com>.
.SH "SEE ALSO"
synce(1)
