.TH "synce-delete-partnership" 1 "SynCE" "http://www.synce.org/"
.SH NAME
synce-delete-partnership \- Delete device partnership
.SH SYNOPSIS
.B synce-delete-partnership
.SH DESCRIPTION
.B synce-delete-partnership
gives a list of partnerships and allows deletion of partnerships.
.SH "AUTHOR"
This man page was written by Jonny Lamb <jonnylamb@jonnylamb.com>.
.SH "SEE ALSO"
synce(1)
