.TH "synce-list-partnerships" 1 "SynCE" "http://www.synce.org/"
.SH NAME
synce-list-partnerships \- List device partnerships
.SH SYNOPSIS
.B synce-list-partnerships
.SH DESCRIPTION
.B synce-list-partnerships
gives a list of partnerships on the device.
.SH "AUTHOR"
This man page was written by Jonny Lamb <jonnylamb@jonnylamb.com>.
.SH "SEE ALSO"
synce(1)
