.TH "synce-create-partnership" 1 "SynCE" "http://www.synce.org/"
.SH NAME
synce-create-partnership \- Create a partnership between device and computer
.SH SYNOPSIS
.B synce-create partnership
.I NAME
.I SYNCITEMS
.SH OPTIONS
.TP
.BI NAME
Name of the partnership.
.TP
.BI SYNCITEMS
Comma-separated list of items you wish to sync from one or more of: Contacts,Calendar,Tasks,Files
.SH "AUTHOR"
This man page was written by Jonny Lamb <jonnylamb@jonnylamb.com>.
.SH "SEE ALSO"
synce(1)
