.TH "synce-clean-partnerships" 1 "SynCE" "http://www.synce.org/"
.SH NAME
synce-clean-partnerships \- Remove device partnerships
.SH SYNOPSIS
.B synce-clean-partnerships
.SH DESCRIPTION
.B synce-clean-partnerships
removes all the partnerships on a connected device.
.SH "AUTHOR"
This man page was written by Jonny Lamb <jonnylamb@jonnylamb.com>.
.SH "SEE ALSO"
synce(1)
